// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuC75VbWFEJqKpgNF-RPeIETViEovc6wc',
    appId: '1:232594799786:web:59ae25cc7353828fc6e4d3',
    messagingSenderId: '232594799786',
    projectId: 'ocean-38e0a',
    authDomain: 'ocean-38e0a.firebaseapp.com',
    storageBucket: 'ocean-38e0a.appspot.com',
    measurementId: 'G-YXTSE53MHP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB75gm8G9ElMQVsX4dmJQqVIouYDMrK6BE',
    appId: '1:232594799786:android:cf93c2fcc006e95ac6e4d3',
    messagingSenderId: '232594799786',
    projectId: 'ocean-38e0a',
    storageBucket: 'ocean-38e0a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmTJTzF5b5DoQ4Mba0P57Bymri3BUoYIM',
    appId: '1:232594799786:ios:6f2e53f9005ce479c6e4d3',
    messagingSenderId: '232594799786',
    projectId: 'ocean-38e0a',
    storageBucket: 'ocean-38e0a.appspot.com',
    iosBundleId: 'com.example.ocean',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmTJTzF5b5DoQ4Mba0P57Bymri3BUoYIM',
    appId: '1:232594799786:ios:6f2e53f9005ce479c6e4d3',
    messagingSenderId: '232594799786',
    projectId: 'ocean-38e0a',
    storageBucket: 'ocean-38e0a.appspot.com',
    iosBundleId: 'com.example.ocean',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuC75VbWFEJqKpgNF-RPeIETViEovc6wc',
    appId: '1:232594799786:web:3820923343506542c6e4d3',
    messagingSenderId: '232594799786',
    projectId: 'ocean-38e0a',
    authDomain: 'ocean-38e0a.firebaseapp.com',
    storageBucket: 'ocean-38e0a.appspot.com',
    measurementId: 'G-SGM1RZZYQC',
  );
}
